name: "pre-commit update"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 7 */7 * *"

permissions:
  contents: write

jobs:
  pre-commit-update:
    runs-on: ubuntu-latest
    env:
      BRANCH: main

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: boidolr/actions/run-precommit@main
        with:
          autoupdate: true

      - name: Push pre-commit changes
        uses: boidolr/actions/git-push@main
        with:
          message: "chore: update pre-commit config"
          branch: "${{ env.BRANCH }}"
